Spender/app/build.gradle.kts, Spender/app/src/main/java/com/example/spender/feature/analysis/AnalysisScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/domain/model/CalendarItemData.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/domain/model/SpendListItemData.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/Calendar.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModelFactory.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/SpendListByDate.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/Graph.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphScreen.kt, Spender/gradle/libs.versions.toml, Spender/settings.gradle.kts
- MP Android Chart 적용
- Calendar tab ui 완성
=> [Feature] MP Android Chart 적용 & Calendar UI 완성

Spender/app/build.gradle.kts, Spender/app/google-services.json, Spender/app/src/main/AndroidManifest.xml, Spender/app/src/main/java/com/example/spender/MainActivity.kt, Spender/app/src/main/java/com/example/spender/feature/auth/AuthScreen.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/AuthViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/GoogleLogin.kt, Spender/app/src/main/java/com/example/spender/ui/theme/navigation/Navigation.kt, Spender/app/src/main/java/com/example/spender/ui/theme/navigation/Screen.kt, Spender/app/src/main/res/values/strings.xml
- 구글로 로그인 하는 기능을 구현하였습니다.
- 자동로그인같은 다른 편의기능은 없으니 참고
firebase와 연동하는 json파일이 바뀌었습니다!
=> [Feat] 구글 로그인 기능 구현

Spender/app/google-services.json, Spender/app/src/main/java/com/example/spender/core/ui/CustomTopAppBar.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/MypageScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/BudgetScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/ExpenseCategoryScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/IncomeCategoryScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/NotificationScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/RegularExpenseScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/component/MyPageItem.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/component/MyPageItemType.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/component/Section.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/ReportDetailScreen.kt, Spender/app/src/main/java/com/example/spender/ui/theme/navigation/Navigation.kt, Spender/app/src/main/java/com/example/spender/ui/theme/navigation/Screen.kt
- 공통 앱바 만들어뒀습니다~! 
- 마이페이지 메인 ui 완료했습니다~!
=> [Feat]  공통 앱바 & 마이페이지 메인 ui 완료

Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/ReportDetailScreen.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/component/BudgetProgressSection.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/component/CategoryPieChart.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/component/EmotionBarChart.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/component/EmotionTagSection.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/detail/component/FeedbackSection.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/list/ReportListScreen.kt
- 리포트 그래프 둥글게 처리
- 리포트 상세 조회 (파이 그래프 & 가로 막대 그래프) 수정
=> [Fix] 리포트 목록 & 상세 그래프 디테일 수정 

Spender/app/src/main/java/com/example/spender/feature/mypage/ui/BudgetScreen.kt
=> [feat] 마이페이지 예산 설정 ui 완료

Spender/app/src/main/java/com/example/spender/MainActivity.kt, Spender/app/src/main/java/com/example/spender/core/data/service/FirebaseAnalysisFunction.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/SpendListItemComponent.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/SpendListByDate.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/Graph.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/GoogleLogin.kt
- 파이어베이스 storage 연결
- ui 변동 없음
- log로 확인됨
=> feat: analysis - database link

Spender/app/build.gradle.kts, Spender/app/src/main/AndroidManifest.xml, Spender/app/src/main/java/com/example/spender/MainActivity.kt, Spender/app/src/main/java/com/example/spender/MyApplication.kt, Spender/app/src/main/java/com/example/spender/feature/auth/AuthScreen.kt, Spender/app/src/main/java/com/example/spender/feature/auth/data/KakaoDataSource.kt, Spender/app/src/main/java/com/example/spender/feature/auth/domain/AuthRepository.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/KakaoLogin.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/viewmodel/SocialViewModel.kt, Spender/app/src/main/res/values/strings.xml, Spender/settings.gradle.kts
- 카카오 로그인이 구현되었습니다. (카카오톡이 아닌 카카오계정으로 했습니다)
- 리팩토링은 추후 예정
=> [Feat] 카카오 소셜 로그인

Spender/app/build.gradle.kts, Spender/gradle/libs.versions.toml
=> [Fix] fcm 버전 낮추기

Spender/app/src/main/java/com/example/spender/feature/mypage/ui/BudgetScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/ExpenseCategoryScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/IncomeCategoryScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/viewmodel/CategoryViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/onboarding/OnboardingScreen.kt, Spender/app/src/main/java/com/example/spender/feature/onboarding/domain/OnboardingRepository.kt, Spender/app/src/main/java/com/example/spender/feature/onboarding/ui/OnboardingViewModel.kt
- 마이페이지/예산설정 화면에서 예산을 수정하는 기능을 구현하였습니다. 테스트 완.
- 온보딩화면에서 예산을 설정하는 기능을 구현하였습니다
- 온보딩화면은 테스트 아직인데 코드 긁어온거라 아마 될 것 같습니다 추후 스플래쉬 화면과 자동로그인까지 구현 후 재테스트 예정
=> [Feat] 예산설정

Spender/app/src/main/java/com/example/spender/feature/analysis/domain/repository/CalendarRepository.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/SpendListByDate.kt
=> fix: income update

Spender/app/src/main/java/com/example/spender/feature/analysis/domain/repository/CalendarRepository.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/domain/repository/GraphRepository.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/Calendar.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/Graph.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphViewModel.kt
- 새로고침 기능 적용
- 다양한 경우에 대한 대응 추가
기능 테스트 완료
=> feat: refresh

Spender/app/src/main/java/com/example/spender/core/data/service/FirebaseMainFunctions.kt, Spender/app/src/main/java/com/example/spender/feature/home/HomeScreen.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/BudgetProgressBar.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/BudgetProgressSection.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/RecentTransactionSection.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/component/BubbleWithText.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/component/BudgetProgressBar.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/component/RecentItem.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/BudgetScreen.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/component/BudgetProgressSection.kt, Spender/app/src/main/res/values/strings.xml
- 홈 화면 DB가 연결되었습니다.
- 월 총 지출액/프로그래스바/최근지출기록5건
- 예산의 100%이상 사용시 프로그래스바가 빨간색으로 변경
- 예산의 ~60% 사용시 / 61~99% 사용시  / 100%~사용시 경고 문구가 달라집니다
=> [Feat] 홈화면 DB 연결

Spender/app/src/main/java/com/example/spender/MainActivity.kt
=> [Design] 바텀앱바 FAB 아이콘 교체 

Spender/.firebaserc, Spender/app/src/main/java/com/example/spender/feature/mypage/MypageScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/domain/model/User.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/viewmodel/MypageViewModel.kt, Spender/firebase.json
- 소셜로그인에 맞게 아이콘과 이름 또는 이메일이 표시될 수 있도록 변경
-
=> [Feat] 마이페이지 소셜로그인별 아이콘/이름 표시

Spender/app/src/main/java/com/example/spender/feature/analysis/domain/repository/CalendarRepository.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/SpendListItemComponent.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/SpendListByDate.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/graph/GraphScreen.kt
- 통계 상세 페이지 UI 수정
- Navigation 수정
=> feat: income/outcome 상세페이지 연결 및 ui 수정

Spender/app/src/main/java/com/example/spender/MainActivity.kt, Spender/app/src/main/java/com/example/spender/feature/auth/AuthScreen.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/KakaoLogin.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/NaverLogin.kt, Spender/app/src/main/java/com/example/spender/feature/auth/ui/viewmodel/AuthViewModel.kt
=> [Feat] 로그인 인디케이터 추가

Spender/app/src/main/java/com/example/spender/feature/mypage/ui/viewmodel/CategoryViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/report/ui/component/ReportCard.kt
=> [Fix] 카테고리 등록 색상 변경

Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/SpendListByDate.kt, Spender/firebase/functions/add-regular-expenses.js, Spender/firebase/functions/create-regular-expenses.js, Spender/firebase/functions/index.js
=> fix: calendar 요일 표기 오류 수정

Spender/firebase/functions/add-regular-expenses.js, Spender/firebase/functions/create-regular-expenses.js
- 정기 지출 functions에 admin, exports 추가했습니다~!
=> [Fix] 정기 지출 functions에 admin, exports 추가

Spender/app/src/main/java/com/example/spender/feature/analysis/ui/calendar/CalendarScreen.kt
=> fix: 요일 버그 수정

Spender/app/src/main/java/com/example/spender/MainActivity.kt, Spender/app/src/main/java/com/example/spender/core/ui/BottomNavigationBar.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/ExpenseCategoryScreen.kt, Spender/app/src/main/java/com/example/spender/feature/mypage/ui/IncomeCategoryScreen.kt
- 네비바와 수입 & 지출 카테고리 fab 버튼 수정했습니다!
=> [Fix] fab 버튼 수정 

Spender/app/src/main/java/com/example/spender/core/common/util/TimeUtils.kt, Spender/app/src/main/java/com/example/spender/core/data/remote/notification/NotificationDto.kt, Spender/app/src/main/java/com/example/spender/feature/home/HomeScreen.kt, Spender/app/src/main/java/com/example/spender/feature/home/domain/Notification.kt, Spender/app/src/main/java/com/example/spender/feature/home/domain/repository/HomeRepository.kt, Spender/app/src/main/java/com/example/spender/feature/home/domain/repository/NotificationListRepository.kt, Spender/app/src/main/java/com/example/spender/feature/home/mapper/NotificationMapper.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/HomeViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/NotificationListScreen.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/NotificationListViewModel.kt, Spender/app/src/main/java/com/example/spender/feature/home/ui/component/NotificationItem.kt, Spender/app/src/main/java/com/example/spender/ui/theme/navigation/Navigation.kt, Spender/firebase/functions/alert/budget-alert.js, Spender/firebase/functions/alert/reminder-alert.js, Spender/firebase/functions/alert/report-alert.js, Spender/firebase/functions/notification-store.js
=> [Feat] 알림 읽음 처리 기능 추가 

Spender/app/build.gradle.kts, Spender/app/src/main/assets/licenses.json, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/domain/model/User.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/ui/ProfileSection.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/ui/component/CircularImage.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/ui/component/MyinfoDialogs.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/ui/viewmodel/MypageViewModel.kt
- 내 정보에서 프로필 사진을 변경/삭제 하는 기능을 구현했습니다 (영상참고)
- 
https://github.com/user-attachments/assets/b85bfc3a-1192-4a0c-b42a-5a8184a55b03
=> [Feat] 프로필 사진 삭제/변경

Spender/app/src/main/java/com/e1i3/spender/core/data/remote/friend/FriendDetailDto.kt, Spender/app/src/main/java/com/e1i3/spender/core/data/remote/friend/FriendListDto.kt, Spender/app/src/main/java/com/e1i3/spender/core/ui/CustomDialog.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/HomeScreen.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/domain/repository/FriendDetailRepository.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/domain/repository/HomeRepository.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/FriendDetailScreen.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/FriendSection.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/component/FirendItem.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/model/FriendDetailUiModel.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/viewModel/FriendDetailViewModel.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/viewModel/HomeViewModel.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/MypageScreen.kt
=> [Feat] 친구 삭제 기능 완료

Spender/app/src/main/java/com/e1i3/spender/feature/home/domain/repository/HomeRepository.kt
- 친구 양방향으로 삭제되도록 추가했습니다!
clean project 후 실행하여 정상 작동 확인했습니다~!
=> [Feat] 친구 양방향 삭제 

Spender/app/src/main/java/com/e1i3/spender/feature/mypage/data/repository/FriendRepository.kt
=> fix: 프로필 정보 추가

Spender/app/src/main/java/com/e1i3/spender/core/data/remote/friend/FriendListDto.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/domain/model/Friend.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/mapper/FriendMapper.kt, Spender/app/src/main/java/com/e1i3/spender/feature/home/ui/component/FirendItem.kt, Spender/app/src/main/java/com/e1i3/spender/feature/mypage/data/repository/FriendRepository.kt, Spender/firebase/functions/notification-store.js
- 프로필 이미지 필드명 photoUrl로 통일
clean project 후 정상작동 확인
=> [Fix] 프로필 이미지 필드명 photoUrl로 통일

Spender/app/src/main/java/com/e1i3/spender/core/ui/TierDialog.kt
- 티어제에 대한 설명이 포함된 다이얼로그를 만들었어요
-
=> [Feat] 티어 관련 다이얼로그

Spender/app/src/main/java/com/e1i3/spender/MainActivity.kt, Spender/app/src/main/java/com/e1i3/spender/feature/expense/ui/ExpenseRegistrationParentScreen.kt, Spender/app/src/main/java/com/e1i3/spender/feature/expense/ui/RegistrationUiState.kt, Spender/app/src/main/java/com/e1i3/spender/feature/expense/ui/RegistrationViewModel.kt
=> [Fix] ocr 막기

Spender/app/src/main/java/com/e1i3/spender/feature/auth/domain/AuthRepository.kt, Spender/app/src/main/java/com/e1i3/spender/feature/onboarding/ui/FirstPage.kt
=> [Fix] 온보딩에서 Ocr내용 주석처리
